### ISSUE TITLE
deprecate meta-mender-kernel; move kernel to boot/esp/efi

### ISSUE THREAD

**Issue by coreycothrum** [coreycothrum/meta-mender-luks#19]
- [ ] Deprecate [meta-mender-kernel](https://github.com/coreycothrum/meta-mender-kernel) and remove dependency.
- [ ] Move A/B kernels from separate partitions to esp/efi (`MENDER/LUKS_KERNEL_DIR`)
- [ ] `mount-rootfs-by-dm-mapper.sh` should/could be removed.
- [ ] Other state scripts may need to change? Yeah, will have to add something to copy the kernel from rootfs to new location on `/boot` partition.

Bonus: I think this will allow #1 to be easily implemented.

**Comment by coreycothrum** [comment]
Investigate migrating to `systemd-boot`

**Comment by coreycothrum** [comment]
Biggest "issue" here is can we cleanly migrate from existing layout to this? Do I need/want to keep this backwards compat?
